#!/bin/sh

# Basic setup
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Set background to grey
xsetroot -solid grey

# Start the Openbox window manager
openbox &
